const levels = {
	beginner: [
		{
			typing: "Their camel was, in this moment, a upbeat nectarine. Some kind pineapples are thought of simply as sheeps. The fly of a grapes becomes a fine octopus. One cannot separate scorpions from nice figs; The modest eagle reveals itself as a courageous sheep to those who look.",
			grades: [],
			speed: [],
			time: [],
			wordLeft: [],
			error: [],
			isCompleted: true,
		},
		{
			typing: "Some assert that authors often misinterpret the fox as a passionate deer, when in actuality it feels more like a creative apricot; This could be, or perhaps the literature would have us believe that a painstaking currant is not but a grapefruit. The receptive nectarine reveals itself as a lively fox to those who look.",
			grades: [],
			speed: [],
			time: [],
			wordLeft: [],
			error: [],
			isCompleted: false,
		},
		{
			typing: "An ant of the fig is assumed to be an exuberant owl. A strawberry of the wolf is assumed to be a vigorous fig. In modern times the puppies could be said to resemble diligent watermelons! This could be, or perhaps a fly is a talented wolf. We can assume that any instance of a grape can be construed as a dynamic grapefruit. Their fish was, in this moment, a bright apricot.",
			grades: [],
			speed: [],
			time: [],
			wordLeft: [],
			error: [],
			isCompleted: false,
		},
		{
			typing: "A delightful pear is a sheep of the mind. An industrious cherry's grapes comes with it the thought that the compassionate tangerine is a tangerine. Though we assume the latter, some rhetorical cows are thought of simply as pandas! Washing and polishing the car,some posit the romantic bird to be less than intelligent. A plucky grapes without rats is truly a raspberry of self-confident cherries. A selective plum's zebra comes with it the thought that the hilarious raspberry is a chicken.",
			grades: [],
			speed: [],
			time: [],
			wordLeft: [],
			error: [],
			isCompleted: false,
		},
		{
			typing: "Authors often misinterpret the rabbit as an exclusive melon, when in actuality it feels more like a sincere scorpion. They were lost without the warm grapefruit that composed their pig. In modern times a strawberry can hardly be considered a shy sheep without also being a turtle. Of course, an eagle is a rational bee. Few can name an eminent crocodile that isn't a pro-active apricot. Some polite cats are thought of simply as zebras? A bear sees a grape as a peaceful kiwi? Waking to the buzz of the alarm clock, their lemon was, in this moment, a friendly pomegranate.",
			grades: [],
			speed: [],
			time: [],
			wordLeft: [],
			error: [],
			isCompleted: false,
		},
	],
	intermediate: [
		{
			typing: "Their camel was, in this moment, a upbeat nectarine. Some kind pineapples are thought of simply as sheeps. The fly of a grapes becomes a fine octopus. One cannot separate scorpions from nice figs; The modest eagle reveals itself as a courageous sheep to those who look.",
			grades: [],
			speed: [],
			time: [],
			wordLeft: [],
			error: [],
			isCompleted: false,
		},
		{
			typing: "Some assert that authors often misinterpret the fox as a passionate deer, when in actuality it feels more like a creative apricot; This could be, or perhaps the literature would have us believe that a painstaking currant is not but a grapefruit. The receptive nectarine reveals itself as a lively fox to those who look.",
			grades: [],
			speed: [],
			time: [],
			wordLeft: [],
			error: [],
			isCompleted: false,
		},
	],
	expert: [],
};
